<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <!-- Только если указана RunMigration=true, проект станет исполняемым -->
        <OutputType Condition="'$(RunMigration)' == 'true'">Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentMigrator" Version="7.1.0" />
        <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
        <PackageReference Include="Npgsql" Version="9.0.3" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>