server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend;
    }

    location ~* ^/inmemoria/ {
        rewrite ^/inmemoria/(.*)$ /$1 break;
        proxy_pass http://takttusur.inmemoria.api;
    }
}