services:
  takttusur.inmemoria.mysql:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: migrationPassword

  takttusur.inmemoria.migrationapp:
    image: takttusur.inmemoria.migrationapp
    depends_on:
      - takttusur.inmemoria.mysql
    build:
      context: .
      dockerfile: TaktTusur.InMemoria.MigrationApp/Dockerfile
